highlighter: rouge
github: [Repository metadata]

baseurl: "http://althouse.co"

collections:
  work:
    output: true
    output_ext: .html
    permalink: /work/:path/

# Sass
sass:
  sass_dir: scss
  style: :expanded
  line_numbers: true