highlighter: pygments
github: [Repository metadata]

baseurl: "http://alt-house.github.io/alt-house-site"

# Permalinks
permalink:   pretty

# Custom Vars
source:      _build
destination: _site
exclude:     [".gitignore", ".editorconfig", "less", "README.md", "config.rb"]

# Sass
sass:
  sass_dir: scss
  style: :expanded
  line_numbers: true
